# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
light: !include lights.yaml

proximity:
  chriserus_coming_home:
    zone: home
    devices:
      - device_tracker.chriserus_mi9
    tolerance: 2
    unit_of_measurement: km

wake_on_lan:
  mac: D8-BB-C1-4B-A8-00

gigasetelements:
  name: gigaset_elements
  username: !secret gigaset_elements_username
  password: !secret gigaset_elements_password
  switches: True
  code: !secret alarm_pin
  code_arm_required: False

device_tracker:
  - platform: xiaomi
    host: !secret router_host
    password: !secret router_password

recorder:
  exclude:
    entities:
      - sensor.next_launch_countdown

vacuum:
  - platform: viomise
    host: !secret vacuum_host
    token: !secret vacuum_token
    name: ViomiSE

camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret vacuum_host
    token: !secret vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ["all"]
    attributes:
      - calibration_points
      - rooms

switch:
  - platform: wake_on_lan
    mac: D8:BB:C1:4B:A8:00
    name: PC

command_line:
  - sensor:
      name: CPU Temperature
      command: "/bin/cat /sys/class/thermal/thermal_zone0/temp"
      unit_of_measurement: "°C"
      value_template: "{{ (value | int / 1000) | int }}"

sensor:
  - platform: random
    name: Random Sensor 1
    maximum: 255
  - platform: random
    name: Random Sensor 2
    maximum: 255
  - platform: random
    name: Random Sensor 3
    maximum: 255
  - platform: template
    sensors:
      living_room_air_purifier_aqi:
        friendly_name: Living Room Air Purifier Air Quality Index
        value_template: "{{ states.fan.living_room_air_purifier.attributes.aqi }}"
        icon_template: mdi:weather-windy

      living_room_air_purifier_temperature:
        friendly_name: Living Room Air Purifier Temperature
        value_template: "{{ states.fan.living_room_air_purifier.attributes.temperature }}"
        unit_of_measurement: "°C"

      living_room_air_purifier_humidity:
        friendly_name: Living Room Air Purifier Humidity
        value_template: "{{ states.fan.living_room_air_purifier.attributes.humidity }}"
        unit_of_measurement: "%"
        icon_template: mdi:water-percent

mqtt:
  sensor:
    - name: "Krzysztof Weight"
      state_topic: "scale/Krzysztof/weight"
      unit_of_measurement: "kg"
      icon: mdi:scale-bathroom

    - name: "Marta Weight"
      state_topic: "scale/Marta/weight"
      unit_of_measurement: "kg"
      icon: mdi:scale-bathroom

history:
  exclude:
    entities:
      - sensor.random_sensor_1
      - sensor.random_sensor_2
      - sensor.random_sensor_3
