# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
    base_url: !secret secure_base_url

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
light: !include lights.yaml
google_assistant: !include google_assistant.yaml

proximity:
  chriserus_coming_home:
    zone: home
    devices:
      - device_tracker.chriserus_mi9
    tolerance: 2
    unit_of_measurement: km

wake_on_lan:
  mac: D8-BB-C1-4B-A8-00

gigasetelements:
  name: gigaset_elements
  username: !secret gigaset_elements_username
  password: !secret gigaset_elements_password
  switches: True
  code: !secret alarm_pin
  code_arm_required: False

device_tracker:
  - platform: xiaomi
    host: !secret router_host
    password: !secret router_password

recorder:
  exclude:
    entities:
      - sensor.next_launch_countdown

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

# media_player:
#   - platform: androidtv
#     name: AndroidTV
#     host: !secret androidtv_host

vacuum:
  - platform: viomise
    host: !secret vacuum_host
    token: !secret vacuum_token
    name: ViomiSE

camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret vacuum_host
    token: !secret vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ["all"]
    attributes:
      - calibration_points
    map_transformation:
      trim:
        top: 50
        bottom: 50
        left: 50
        right: 50

fan:
  - platform: xiaomi_miio_airpurifier
    host: !secret fan_host
    token: !secret fan_token
    name: Fan

switch:
  - platform: template
    switches:
      living_room_air_purifier_child_lock:
        friendly_name: "Child lock"
        value_template: "{{ is_state_attr('fan.living_room_air_purifier', 'child_lock', True) }}"
        turn_on:
          service: xiaomi_miio_airpurifier.fan_set_child_lock_on
          data:
            entity_id: fan.living_room_air_purifier
        turn_off:
          service: xiaomi_miio_airpurifier.fan_set_child_lock_off
          data:
            entity_id: fan.living_room_air_purifier
        icon_template: "mdi:lock-outline"

      living_room_air_purifier_buzzer:
        friendly_name: "Buzzer"
        value_template: "{{ is_state_attr('fan.living_room_air_purifier', 'buzzer', True) }}"
        turn_on:
          service: xiaomi_miio_airpurifier.fan_set_buzzer_on
          data:
            entity_id: fan.living_room_air_purifier
        turn_off:
          service: xiaomi_miio_airpurifier.fan_set_buzzer_off
          data:
            entity_id: fan.living_room_air_purifier
        icon_template: "mdi:volume-off"

      living_room_air_purifier_led:
        friendly_name: "LED"
        value_template: "{{ is_state_attr('fan.living_room_air_purifier', 'led', True) }}"
        turn_on:
          service: xiaomi_miio_airpurifier.fan_set_led_on
          data:
            entity_id: fan.living_room_air_purifier
        turn_off:
          service: xiaomi_miio_airpurifier.fan_set_led_off
          data:
            entity_id: fan.living_room_air_purifier
        icon_template: "mdi:lightbulb-outline"
  - platform: wake_on_lan
    mac: D8:BB:C1:4B:A8:00
    name: PC

sensor:
  - platform: command_line
    name: CPU Temperature
    command: "/bin/cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: "{{ (value | int / 1000) | int }}"
  - platform: template
    sensors:
      living_room_air_purifier_aqi:
        friendly_name: Living Room Air Purifier Air Quality Index
        value_template: "{{ states.fan.living_room_air_purifier.attributes.aqi }}"
        icon_template: mdi:weather-windy

      living_room_air_purifier_temperature:
        friendly_name: Living Room Air Purifier Temperature
        value_template: "{{ states.fan.living_room_air_purifier.attributes.temperature }}"
        unit_of_measurement: "°C"

      living_room_air_purifier_humidity:
        friendly_name: Living Room Air Purifier Humidity
        value_template: "{{ states.fan.living_room_air_purifier.attributes.humidity }}"
        unit_of_measurement: "%"
        icon_template: mdi:water-percent

  - platform: mqtt
    name: "Krzysztof Weight"
    state_topic: "scale/Krzysztof/weight"
    unit_of_measurement: "kg"
    icon: mdi:scale-bathroom

  - platform: mqtt
    name: "Marta Weight"
    state_topic: "scale/Marta/weight"
    unit_of_measurement: "kg"
    icon: mdi:scale-bathroom

binary_sensor:
  - platform: iss
    show_on_map: true
